-- MySQL Script generated by MySQL Workbench
-- 04/11/15 16:02:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema negocio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `negocio` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `negocio` ;

-- -----------------------------------------------------
-- Table `negocio`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Usuario` (
  `UsuarioID` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(150) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `NombreCompleto` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UsuarioID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Negocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Negocio` (
  `NegocioID` INT NOT NULL AUTO_INCREMENT,
  `UsuarioID` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  `Descripcion` VARCHAR(4000) NULL,
  `Email` VARCHAR(150) NULL,
  `Telefono` VARCHAR(20) NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NegocioID`),
  INDEX `fk_Negocio_Usuario1_idx` (`UsuarioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`NegocioFavorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`NegocioFavorito` (
  `NegocioFavoritoID` INT NOT NULL AUTO_INCREMENT,
  `UsuarioID` INT NOT NULL,
  `NegocioID` INT NOT NULL,
  `Fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NegocioFavoritoID`),
  INDEX `fk_NegocioFavorito_Usuario1_idx` (`UsuarioID` ASC),
  INDEX `fk_NegocioFavorito_Negocio1_idx` (`NegocioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`NegocioPublicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`NegocioPublicacion` (
  `NegocioPublicacionID` INT NOT NULL AUTO_INCREMENT,
  `NegocioID` INT NOT NULL,
  `Fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Titulo` VARCHAR(250) NULL,
  `Descripcion` VARCHAR(4000) NULL,
  PRIMARY KEY (`NegocioPublicacionID`),
  INDEX `fk_NegocioPublicacion_Negocio1_idx` (`NegocioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`PublicacionFavorita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`PublicacionFavorita` (
  `PublicacionFavoritaID` INT NOT NULL AUTO_INCREMENT,
  `NegocioPublicacionID` INT NOT NULL,
  `UsuarioID` INT NOT NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PublicacionFavoritaID`),
  INDEX `fk_PublicacionFavorita_NegocioPublicacion1_idx` (`NegocioPublicacionID` ASC),
  INDEX `fk_PublicacionFavorita_Usuario1_idx` (`UsuarioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Contacto` (
  `ContactoID` INT NOT NULL AUTO_INCREMENT,
  `NegocioID` INT NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Apellido` VARCHAR(150) NOT NULL,
  `Telefono` VARCHAR(20) NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Direccion` VARCHAR(300) NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ContactoID`),
  INDEX `fk_Contacto_Negocio_idx` (`NegocioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`TipoNegocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`TipoNegocio` (
  `TipoNegocioID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Descricipcion` VARCHAR(450) NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TipoNegocioID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Categoria` (
  `CategoriaID` INT NOT NULL AUTO_INCREMENT,
  `TipoNegocioID` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  `Descripcion` VARCHAR(400) NULL,
  `Url` VARCHAR(450) NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CategoriaID`, `TipoNegocioID`),
  INDEX `fk_Categoria_TipoNegocio1_idx` (`TipoNegocioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`NegocioCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`NegocioCategoria` (
  `NegocioCategoriaID` INT NOT NULL AUTO_INCREMENT,
  `NegocioID` INT NOT NULL,
  `CategoriaID` INT NOT NULL,
  `Fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NegocioCategoriaID`),
  UNIQUE INDEX `Fecha_UNIQUE` (`Fecha` ASC),
  INDEX `fk_NegocioCategoria_Negocio1_idx` (`NegocioID` ASC),
  INDEX `fk_NegocioCategoria_Categoria1_idx` (`CategoriaID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`NegocioUbicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`NegocioUbicacion` (
  `NegocioUbicacionID` INT NOT NULL AUTO_INCREMENT,
  `NegocioID` INT NOT NULL,
  `Latitud` DECIMAL NULL,
  `Longitud` DECIMAL NULL,
  `Direccion` VARCHAR(250) NOT NULL,
  `Descripcion` VARCHAR(400) NULL,
  `Fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NegocioUbicacionID`),
  INDEX `fk_NegocioUbicacion_Negocio1_idx` (`NegocioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`NegocioPuntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`NegocioPuntuacion` (
  `NegocioPuntuacionID` INT NOT NULL AUTO_INCREMENT,
  `UsuarioID` INT NOT NULL,
  `NegocioID` INT NOT NULL,
  `Puntuacion` INT NULL,
  `Fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NegocioPuntuacionID`),
  INDEX `fk_NegocioPuntuacion_Usuario1_idx` (`UsuarioID` ASC),
  INDEX `fk_NegocioPuntuacion_Negocio1_idx` (`NegocioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`PublicacionPuntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`PublicacionPuntuacion` (
  `PublicacionPuntuacionID` INT NOT NULL AUTO_INCREMENT,
  `NegocioPublicacionID` INT NOT NULL,
  `UsuarioID` INT NOT NULL,
  `Puntuacion` INT NOT NULL DEFAULT 0,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PublicacionPuntuacionID`),
  INDEX `fk_PublicacionPuntuacion_NegocioPublicacion1_idx` (`NegocioPublicacionID` ASC),
  INDEX `fk_PublicacionPuntuacion_Usuario1_idx` (`UsuarioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`NegocioImagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`NegocioImagen` (
  `NegocioImagenID` INT NOT NULL AUTO_INCREMENT,
  `NegocioID` INT NOT NULL,
  `Url` VARCHAR(500) NOT NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NegocioImagenID`),
  INDEX `fk_NegocioImagen_Negocio1_idx` (`NegocioID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`PublicacionImagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`PublicacionImagen` (
  `PublicacionImagenID` INT NOT NULL AUTO_INCREMENT,
  `NegocioPublicacionID` INT NOT NULL,
  `Url` VARCHAR(500) NULL,
  `Fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PublicacionImagenID`),
  INDEX `fk_PublicacionImagen_NegocioPublicacion1_idx` (`NegocioPublicacionID` ASC))
ENGINE = InnoDB;

CREATE TABLE `validacion` (
  `ValidacionID` int(11) NOT NULL AUTO_INCREMENT,
  `UsuarioID` varchar(13) NOT NULL,
  `FechaCreacion` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CodigoSecreto` varchar(48) NOT NULL,
  `Tipo` varchar(25) NOT NULL,
  `FechaModificacion` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Estado` tinyint(1) NOT NULL DEFAULT '1',
  `Valores` varchar(50) NOT NULL,
  PRIMARY KEY (`ValidacionID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

ALTER TABLE usuario ADD Activo tinyint(4);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
